# 1. insert dependencies
linked_list.o: 
	gcc -c linked_list.c

# 2. insert dependencies
# 3. complete gcc command
main:
	gcc -o main main.o linked_list.o

run: main
	./main

.PHONY: clean

clean:
	rm linked_list.o main