# TODO: complete recipe main
main: 

file1.o: file1.c file1.h
	gcc -c file1.c file1.h

# TODO: complete recipe file2~4
file2.o: 

file3.o: 

file4.o: 

main.o: main.c main.h
	gcc -c main.c main.h

.PHONY: clean

clean :
	rm *.o

